### ISSUE TITLE
Xuabble

### ISSUE THREAD

**Issue by gingerchew** [MelSumner/collective-nouns#18]
"A Xuabble of Xeets is the responses or quote xeets that spawn from an especially hot/unpleasant take."

I think Quabble should stay thought

**Comment by MelSumner** [comment]
@gingerchew I was also wondering if Quabble should maybe stay but remove Twitter references and instead reference "a social media post" which is more generic. WDYT?

**Comment by gingerchew** [comment]
I like that idea!
